import pywhatkit

# Replace with the recipient's phone number (including country code)
phone_number = "000000000"

# The message you want to send
message = "ignore this is a automatic msg generated by pywhatkit \n testing purpose"

# Send the message instantly
try:
    pywhatkit.sendwhatmsg_instantly(phone_number, message)
    print("Message sent instantly!")
except Exception as e:
    print(f"An error occurred: {e}")
